# This file was created using H3restore tool v1.6.1
# For source code, refer to https://github.com/vppillai/H3Restore 

compiler: null
creation_date: '2021-07-14T12:16:43.603178'
mhc_mode: Standalone
mhc_version: v3.8.0
modules:
- name: bsp
  version: v3.9.0
- name: CMSIS-FreeRTOS
  version: v10.3.1
- name: core
  version: v3.9.2
- name: crypto
  version: v3.7.1
- name: cryptoauthlib
  version: v3.3.2
- name: csp
  version: v3.9.1-rc.2-106-g327b047e0
- name: dev_packs
  version: v3.9.0
- name: mhc
  version: v3.8.0
- name: net
  version: v3.7.0
- name: paho.mqtt.embedded-c
  version: v1.2.2
- name: quick_docs
  version: v1.3.0
- name: touch
  version: v3.9.2
- name: usb
  version: v3.8.0
- name: wireless_system_pic32mzw1_wfi32e01
  version: v3.4.1-31-g972a78e
- name: wireless_wifi
  version: v3.4.0-465-g3a5a3500
- name: wolfMQTT
  version: v1.7.1
- name: wolfssl
  version: v4.7.0
- name: zlib
  version: v1.2.11
operating_system: Windows 10
project: H3Restore
