configName: pic32mzw1_refdesign
folderName: pic32mzw1_refdesign_oob
format_version: v1.0
frameworkPath: D:\H3_Internal_B0
processor: PIC32MZ1025W104132
projectName: pic32mzw1_refdesign_oob
settings:
  PackageFilter: bsp;core;crypto;cryptoauthlib;csp;net;quick_docs;touch;usb;wireless_system_pic32mzw1_wfi32e01;wireless_wifi
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_RECENT
  DFPPath: .\dev_packs\Microchip\PIC32MZ-W_DFP\1.4.193\atdf\PIC32MZ1025W104132.atdf
